### ISSUE TITLE
404 not found for https://api.robinhood.com/oauth2/migrate_token/

### ISSUE THREAD

**Issue by doctorcolossus** [mstrum/robinhood-python#30]
The login script seemed to work fine for me, but I get the following error when trying to place or cancel orders using the respective scripts:

```
Traceback (most recent call last):
  File "~/robinhood-python/robinhood/RobinhoodClient.py", line 50, in _raise_on_error
    response.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.robinhood.com/oauth2/migrate_token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cancel_crypto.py", line 32, in <module>
    orders = client.get_crypto_orders()
  File "~/robinhood-python/robinhood/RobinhoodClient.py", line 2188, in get_crypto_orders
    response = self._get_session(NUMMUS, authed=True, oauth2=True).get(NUMMUS_HOST + 'orders/')
  File "~/robinhood-python/robinhood/RobinhoodClient.py", line 102, in _get_session
    self.ensure_valid_oauth2_token()
  File "~/robinhood-python/robinhood/RobinhoodClient.py", line 132, in ensure_valid_oauth2_token
    self.migrate_token()
  File "~/robinhood-python/robinhood/RobinhoodClient.py", line 121, in migrate_token
    _raise_on_error(response)
  File "~/robinhood-python/robinhood/RobinhoodClient.py", line 59, in _raise_on_error
    raise NotFound()
robinhood.exceptions.NotFound
```

Indeed, I get the same error for this URL in my browser.

**Comment by mstrum** [comment]
One possibility is always going to be that they turn this off at any point in time, so I wouldn't be surprised if one day it just all stops working.

**Comment by zbirnba1** [comment]
I got the same error starting today (yesterday everything was fine), it seems that standard (not oauth2) token still works...for now.

**Comment by zbirnba1** [comment]
Not all endpoints require oauth2. If you go through the endpoints [here](https://github.com/mstrum/robinhood-python/blob/master/robinhood/RobinhoodClient.py) the methods where the response uses authed=True should still work, while those with oauth2=True will likely fail.  It seems that the functionality around crypto/options all use oauth2 but standard equities use the traditional auth token set by the "set_auth_token_with_credentials" method.

**Comment by doctorcolossus** [comment]
Ah, thanks for that explanation.
Unfortunately it was primarily crypto I was interested in trading, so it looks like that won't be possible unless/until an alternative to this URL is discovered and major API changes don't occur.

**Comment by sdmiami** [comment]
Found it from another REPO 

The new way of getting the OAuth2 tokens. Looks like you no longer need to migrate the old tokens.
Now you can simply send a POST request to https://api.robinhood.com/oauth2/token/ with the following data:

client_id: 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS'
expires_in: 86400
grant_type: 'password'
password: <your_password>
scope: 'internal'
username: <your_username>

It returns what was returned by https://api.robinhood.com/oauth2/migrate_token/

**Comment by mstrum** [comment]
It'll be interesting to see what they do about the client_id, since I assume that's the client_id for the Robinhood app and that they will eventually move towards giving out client ids and keys.  For now that will probably work though.

**Comment by SOGorman35** [comment]
> Ah, thanks for that explanation.
> Unfortunately it was primarily crypto I was interested in trading, so it looks like that won't be possible unless/until an alternative to this URL is discovered and major API changes don't occur.

I don't know if you are still looking to use the API to trade crypto, but after a few days of messing around with things in my spare time (my only programming experience is with learning just enough Python to be able to write working strategies in Quantopian, and later, Catalyst, which is essentially identical), I was able to get crypto working.  The only issues I have are 1) when the token expires after 1 day, I don't know how to refresh to get a new one (which isn't a big deal since trading pauses for about 30 minutes for maintenance at the same time every day), and 2) I'm struggling to figure out the best field to use for determining how much cash I have available when executing a new order.  The "cash" field in accounts seems to treat trading crypto the same as trading stocks, where it doesn't settle for 3 days, even though you can just buy and sell crypto repeatedly without issue.  There are a couple of fields in margin_balances that more accurately reflect your buying power, but they don't seem to be 100% correct, so I sometimes end up trying to buy more than I have the ability to.  I'm only playing with $100 right now while I figure out how everything works and if trading crypto is even worth it on Robinhood.  I was hoping to take advantage of the lack of fees and the presumed lack of bots on the platform, but the bid and ask prices quoted in the app and by the API don't seem to accurately reflect what you can actually buy and sell crypto for on Robinhood.
